# General Jekyll Config
encoding: utf-8
#pygments: true
url: http://vivlong.github.io
safe: true
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
#permalink: /blog/:year/:month/:day/:title.html
auto: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
#markdown: rdiscount 
#paginate: 13
#paginate_path: "page:num"

# White-listed plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  
# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#3498db'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: vivlong
    #bitbucket:  
    #hacker_news: vivlong
    #stackexchange: 2531052 
    stackoverflow: 2531052 
    #twitter: flyinit
    #facebook: liaozheng 
    #tumblr: 
    linkedin: james-liao-95a31a103
    gplus: 113114172117752769682
    weibo: flyintech
    #rss:

  name: 廖小正
  email: vivlong@163.com
  tagline: "Lighting candles in the dark."

  # Google Analytics key, leave blank to ignore
  google_analytics_key:
  
  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false
  
  show_related: false
